name: iso_duration_parser
description: A starting point for Dart libraries or applications.
homepage: https://github.com/mzdm/iso_duration_parser
version: 0.1.0

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
