name: iso_duration_parser
description: A package which parses ISO 8061 Duration (PnYnMnDTnHnMnS format).
homepage: https://github.com/denisano/iso_duration_parser (fork from https://github.com/mzdm/iso_duration_parser)
version: 1.2.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.14
