on: [ push, pull_request ]
name: tests
jobs:
  build:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Flutter action
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '2.12.0'
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
