on: [ push, pull_request ]
name: tests
jobs:
  build:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dart action
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '2.12.0'
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
      - name: Install test_coverage
        run: pub global activate test_coverage
      - name: Run test_coverage
        run: pub global run test_coverage
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info